version: '3.2'

services:
  app:
    image: mass6/lemp:latest
    ports:
     - "80:80"
    volumes:
     - .:/var/www/html
    networks:
     - elasticlaravel

  mysql:
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elasticlaravel
      MYSQL_USER: elasticlaravel
      MYSQL_PASSWORD: elasticlaravel
    volumes:
      - elasticlaravel:/var/lib/mysql
    networks:
      - elasticlaravel

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - elasticlaravel

  elasticsearch:
    build:
      context: ./elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elk/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elasticlaravel

  kibana:
    build:
      context: ./elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elk/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elasticlaravel
    depends_on:
      - elasticsearch

networks:
  elasticlaravel:
    driver: bridge

volumes:
  elasticsearch:
  elasticlaravel:
    driver: "local"
